### ISSUE TITLE
issues pour le back-end by tyron kadoche

### ISSUE THREAD

**Issue by Tydem** [neoconnect-EIP/neoconnect-Web#6]
request hs:
- PUT inf/me
- GET offer/apply/user/id

ajout des champs:
- mark
- comments

dans la requete get /shop/id

besoin de DATA dans Offer/list et des profilePic pour les shop déja existant

**Comment by Mystogunn** [comment]
Je peut avoir plus de detail sur le bug de la request PUT inf/me stp

et aussi la request GET offer/apply/user/id decrit moi le bug parce que la moi sa fonctionne

et pour les comment et mark sont deja integrer la request get /shop/id
